name: reaxit
description: The newest ThaliApp. Now in Flutter.

# Do not publish to pub.dev
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.1.2+1

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Annotations.
  meta: ^1.7.0

  # Nice functions for collections.
  collection: ^1.16.0

  # Fonts.
  google_fonts: ^3.0.1

  # DateTime formatting.
  intl: ^0.17.0

  # Networking basics.
  http: ^0.13.4
  http_parser: ^4.0.0

  # OAuth2 authorized http Client.
  oauth2: ^2.0.0

  # Secure storage for OAuth2 credentials.
  flutter_secure_storage: ^6.0.0

  # JSON parsing.
  json_annotation: ^4.4.0

  # BLoC state management.
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

  # Persistent storage.
  shared_preferences: ^2.0.11

  # Opening urls.
  url_launcher: ^6.1.4

  # Authenticating in browser.
  flutter_web_auth:
    # flutter_web_auth is not compatible with flutter 3.0.x yet. The fix has not 
    # been released yet, so we temporarily reference the fix by a git reference.
    # TODO: Remove this when the fix is released. See: https://github.com/LinusU/flutter_web_auth/pull/118
    git:
      url: https://github.com/noga-dev/flutter_web_auth.git
      ref: a49488592f9eeeec3c75ae9335ed51ae84f2a2b0

  # Modal photo views.
  photo_view: ^0.14.0

  # HTML widget.
  flutter_widget_from_html_core: ^0.8.4

  # Sentry error reporting.
  sentry_flutter: ^6.5.1

  # Share menu.
  share_plus: ^4.0.3

  # Path for temporary files.
  path_provider: ^2.0.6
  
  # Access camera and gallery.
  image_picker: ^0.8.4+4
  gallery_saver: ^2.3.2

  # Resize images.
  image_cropper: ^2.0.3

  # Carousel.
  carousel_slider: ^4.0.0

  # Firebase for push notifications.
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6

  # Push notifications in app. 
  overlay_support: ^2.0.0

  # Sticky headers for calendar.
  sticky_headers: ^0.3.0

  # Predefined animations.
  animations: ^2.0.3

  # Export event to calendar.
  add_2_calendar: ^2.1.3

  # Cached images.
  cached_network_image: ^3.2.1
  flutter_cache_manager: ^3.3.0

  # Navigation.
  go_router: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  # JSON parsing.
  build_runner: ^2.1.2

  # JSON parsing.
  json_serializable: ^6.1.3

  # Linting.
  flutter_lints: ^2.0.1

  # Generating splash screens.
  flutter_native_splash: ^1.2.3

  mockito: ^5.2.0

# The following section is specific to Flutter.
flutter:

  # Include Material Icons font.
  uses-material-design: true

  assets:
    - assets/img/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
