name: reaxit
description: The newest ThaliApp. Now in Flutter.

# Do not publish to pub.dev
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Annotations.
  meta: ^1.7.0

  # Fonts.
  google_fonts: ^2.1.0

  # DateTime formatting.
  intl: ^0.17.0

  # Networking basics.
  http: ^0.13.4
  http_parser: ^4.0.0

  # OAuth2 authorized http Client.
  oauth2: ^2.0.0

  # Secure storage for OAuth2 credentials.
  flutter_secure_storage: ^4.2.1

  # JSON parsing.
  json_annotation: ^4.1.0

  # BLoC.
  flutter_bloc: ^7.3.0
  equatable: ^2.0.3

  # Persistent storage.
  shared_preferences: ^2.0.8

  # Opening urls.
  url_launcher: ^6.0.11

  # Authenticating in browser.
  flutter_web_auth: ^0.3.1

  # Modal photo views.
  photo_view: ^0.13.0

  # HTML widget.
  flutter_widget_from_html_core: ^0.7.0

  # Sentry error reporting.
  sentry_flutter: ^6.0.1

  # Share menu.
  share_plus: ^2.2.0

  # Path for temporary files.
  path_provider: ^2.0.5
  
  # Access camera and gallery.
  image_picker: ^0.8.4+2

  # Resize images.
  image_cropper: ^1.4.1

  # Carousel.
  carousel_slider: ^4.0.0

  # Firebase for push notifications.
  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.7

  # Push notifications in app. 
  overlay_support: ^1.2.1

  # Sticky headers for calendar.
  sticky_headers: ^0.2.0

  # Predefined animations
  animations: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # JSON parsing.
  build_runner: ^2.1.2

  # JSON parsing.
  json_serializable: ^5.0.2

  # Linting.
  flutter_lints: ^1.0.4

  # Generating splash screens.
  flutter_native_splash: ^1.2.3

# The following section is specific to Flutter.
flutter:

  # Include Material Icons font.
  uses-material-design: true

  assets:
    - assets/img/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
